# .github/workflows/ruff_ty_weekly.yml
name: ruff_ty_weekly

on:
  schedule:
    # Sunday 09:00 UTC (05:00 America/New_York)
    - cron: "0 9 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  weekly-format-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main               # Always run from the main branch

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install Ruff + Ty + deps
      run: |
        python -m pip install --upgrade pip
        pip install --pre "ruff>=0.4.0" ty
        [[ -f requirements.txt ]] && pip install -r requirements.txt
        pip install pandas-stubs

    - name: Ruff – format & lint repo
      run: |
        ruff format .
        ruff check . --fix

    - name: Create/Update PR with fixes
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: "style: weekly Ruff auto‑format [skip ci]"
        branch: chore/ruff-weekly-fixes
        base: main              # PR will always target main
        title: "chore: weekly Ruff auto‑format"
        body: |
          Automated weekly run of Ruff (format, lint, type‑check).
          _Generated by `.github/workflows/ruff_ty_weekly.yml`._
        delete-branch: true

