# .github/workflows/ruff_ty_check.yml
name: ruff_ty_check

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  format-lint:
    concurrency:
      group: format-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # -------------------- fixed indentation here --------------------
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # ----------------------------------------------------------------

      # Install tools once
      - name: Install Ruff + Ty
        run: |
          python -m pip install --upgrade pip
          pip install --pre "ruff>=0.4.0" "ty>=0.0.1a0"

      - name: Install project dependencies + type stubs
        run: |
          # Runtime deps
          pip install -r requirements.txt

          # ---- Extra PEP 561 stub wheels so `ty` can resolve imports ----
          # These are *only* compile-time aids; they add **zero** runtime cost.
          pip install \
            pandas-stubs \

      # Work out which .py files changed in the push/PR
      - name: Determine changed Python files
        id: changed
        shell: bash
        run: |
          BASE_SHA="${{ github.event.before }}"
          if [ -z "$BASE_SHA" ] || [ "$BASE_SHA" = "0000000000000000000000000000000000000000" ]; then
            BASE_SHA="$(git rev-parse HEAD~1)"
          fi
          BASE_SHA="$(git merge-base "$BASE_SHA" "$GITHUB_SHA")"
          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" "$GITHUB_SHA" -- '*.py' | sort -u | tr '\n' ' ')
          echo "files=$CHANGED_FILES" >> "$GITHUB_OUTPUT"

      - name: Nothing to do
        if: ${{ steps.changed.outputs.files == '' }}
        run: echo "No Python files changed – skipping formatting, linting and type-checking."

      # ----- Ruff driven entirely by your TOML -----
      - name: Ruff – format
        if: ${{ steps.changed.outputs.files != '' }}
        run: |
          ruff format ${{ steps.changed.outputs.files }}

      - name: Ruff – lint & auto-fix
        if: ${{ steps.changed.outputs.files != '' }}
        run: |
          ruff check ${{ steps.changed.outputs.files }} --fix

      # ----- Ty static type checking -----
      - name: Ty – type check (informational only)
        if: ${{ steps.changed.outputs.files != '' }}
        continue-on-error: true  # Do not fail CI while Ty is still alpha
        run: |
          ty check ${{ steps.changed.outputs.files }}

      # ----- Commit any modifications back to the branch -----
      - name: Commit & push (if needed)
        if: ${{ steps.changed.outputs.files != '' }}
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "style: auto-format changed files with ruff [skip ci]"
            git push
          else
            echo "Nothing to commit – changed files already tidy."
          fi
  
